### ISSUE TITLE
Support clang-tidy-13

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#11]
It would great to have support for the latest version of `clang-tidy` :+1:

**Comment by ghutchis** [comment]
AFAICT `clang-tidy-11` is already part of the `focal` universe:
https://packages.ubuntu.com/focal-updates/clang-tidy-11

**Comment by vadi2** [comment]
Sure, but I mean `12`

**Comment by ghutchis** [comment]
I know - but `clang-tidy-12` isn't yet available for focal, so AFAIK, it's not just a quick `Dockerfile` update.

**Comment by ZedThree** [comment]
I guess if LLVM 12 is available from a reputable PPA, that would work?

**Comment by ghutchis** [comment]
I'm not a Dockerfile expert.. Worth a try:
https://packages.ubuntu.com/hirsute/clang-tidy-12

**Comment by vadi2** [comment]
clang-tidy-13 is out now and adds some great checks such as https://clang.llvm.org/extra/clang-tidy/checks/readability-function-cognitive-complexity.html, would be great to make use of it in PRs - sometimes people contribute functions way too big.

**Comment by ZedThree** [comment]
I've added clang-tidy-12. I think it's important that the base image is something fairly standard, otherwise it could be painful to support most people's workflows. This means that supporting the latest clang-tidy as it's released is probably a no-go I'm afraid.

If someone knows how to make the base image be an argument from the Action, then PRs are very much welcome :)
