### ISSUE TITLE
Support .clang-tidy

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#9]
.clang-tidy file is a great tool to have one, consistent place for all the checks - would be great if the action supported it out of the box.

**Comment by ZedThree** [comment]
This shouldn't be too difficult -- it might even work already!

**Comment by 2bndy5** [comment]
according to the latest `clang-tidy10 --help`:
```
--config=<string>              -
                                   Specifies a configuration in YAML/JSON format:
                                     -config="{Checks: '*',
                                               CheckOptions: [{key: x,
                                                               value: y}]}"
                                   When the value is empty, clang-tidy will
                                   attempt to find a file named .clang-tidy for
                                   each source file in its parent directories.
```
So, maybe it could be made explicit by setting `clang_tidy_checks` input to a empty or zero-length string. I don't see the docs saying that the `.clang-tidy` file is automatically sought which kinda makes sense because it would collid with the `-checks=`  option.
